version: "3.8"
name: llmtoolflow 

services:
  handler:
    build:
      context: ./handler
      dockerfile: Dockerfile
    container_name: llmtoolflow-handler 
    ports:
      - "9000:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} 
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./handler/src:/var/task/src
