version: "3.8"
name: infra-chatbot

services:
  postgres:
    image: postgres:16.8
    container_name: infra-chatbot-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: infra-chatbot-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: infra-chatbot-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redisdata:/data

  handler:
    build:
      context: ./handler
      dockerfile: Dockerfile
    container_name: infra-chatbot-handler
    ports:
      - "8000:8000"
    env_file: ./handler/.env 
    volumes:
      - ./handler/src:/opt/program/src
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  redisdata:
