name: llmtoolflow

services:
  db:
    image: postgres:latest
    container_name: llmtoolflow-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: llmtoolflow_db

  redis:
    image: redis/redis-stack:latest
    container_name: llmtoolflow-redis
    ports:
      - "6379:6379"
      - "8001:8001"
