name: API 

on:
  pull_request:
    branches:
      - main
    paths:
      - 'chatbot/api/**'
      - '.github/workflows/api.yml'
      - 'deploy/infra/**'
    types:
      - closed

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-test:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python dependencies
        working-directory: chatbot/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        working-directory: chatbot/api
        run: |
          pip install pytest
          pytest
